-- MySQL Script generated by MySQL Workbench
-- Sat Jul  8 17:54:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db1` ;
USE `db1` ;

-- -----------------------------------------------------
-- Table `db1`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db1`.`inventory` (
  `i_id` INT NOT NULL,
  `gender` CHAR(1) NOT NULL,
  `product` VARCHAR(15) NOT NULL,
  `quantity` INT(11) NOT NULL,
  `amt` FLOAT NOT NULL,
  `room_no` VARCHAR(5) NOT NULL,
  `tot_amt` FLOAT NOT NULL,
  PRIMARY KEY (`i_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db1`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db1`.`Students` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(15) NULL,
  `Gender` CHAR NULL,
  `Age` INT NULL,
  `Join Date` DATE NULL,
  `Class` INT NULL,
  `Grade` CHAR NULL,
  `Medical Report` LONGBLOB NULL,
  `Schooling` VARCHAR(15) NULL,
  `Inventory_ID` INT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `Inventory_ID_idx` (`Inventory_ID` ASC),
  CONSTRAINT `Inventory_ID`
    FOREIGN KEY (`Inventory_ID`)
    REFERENCES `db1`.`inventory` (`i_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db1`.`Staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db1`.`Staff` (
  `Staff ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(15) NULL,
  `Gender` CHAR NULL,
  `Age` INT NULL,
  `Salary` INT NULL,
  `Designation` VARCHAR(15) NULL,
  PRIMARY KEY (`Staff ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db1`.`Achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db1`.`Achievements` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `Category` VARCHAR(15) NULL,
  `Rank` INT NULL,
  PRIMARY KEY (`StudentID`),
  CONSTRAINT `StudentID`
    FOREIGN KEY (`StudentID`)
    REFERENCES `db1`.`Students` (`StudentID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db1`.`donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db1`.`donor` (
  `d_id` INT NOT NULL,
  `d_name` VARCHAR(15) NOT NULL,
  `d_loc` VARCHAR(25) NOT NULL,
  `d_occupation` VARCHAR(15) NOT NULL,
  `d_money` FLOAT NOT NULL,
  `d_email` VARCHAR(25) NOT NULL,
  `d_phno` DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (`d_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `db1`.`finance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db1`.`finance` (
  `f_id` INT NOT NULL,
  `f_amt` FLOAT NOT NULL,
  `purpose` VARCHAR(15) NOT NULL,
  `f_date` DATE NOT NULL,
  `f_sid` INT NULL,
  `f_did` INT NULL,
  PRIMARY KEY (`f_id`),
  INDEX `f_sid_idx` (`f_sid` ASC),
  INDEX `f_did_idx` (`f_did` ASC),
  CONSTRAINT `f_sid`
    FOREIGN KEY (`f_sid`)
    REFERENCES `db1`.`Staff` (`Staff ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `f_did`
    FOREIGN KEY (`f_did`)
    REFERENCES `db1`.`donor` (`d_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
